# Generated by Django 4.1 on 2023-02-14 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaTecnica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido',
            new_name='apellido_materno',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
