# Generated by Django 4.1 on 2023-02-14 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaTecnica', '0002_rename_apellido_estudiante_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='horario',
        ),
        migrations.AddField(
            model_name='curso',
            name='horario_fin',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='horario_inicio',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
