# Generated by Django 4.1 on 2023-02-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaTecnica', '0003_remove_curso_horario_curso_horario_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinscripcion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
