# Generated by Django 4.1 on 2023-02-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaTecnica', '0004_detalleinscripcion_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PruebaTecnica.curso'),
        ),
        migrations.AlterField(
            model_name='detalleinscripcion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PruebaTecnica.estudiante'),
        ),
    ]
